### ISSUE TITLE
cannot be converted to a number.

### ISSUE THREAD

**Issue by ShenYunyao1** [AfternoonMatcha/WuHua-Gacha-OCR-Export-Power-Automate#1]
![图片](https://github.com/user-attachments/assets/785e8683-6755-48c0-9824-2ba48865096c)

**Comment by ShenYunyao1** [comment]
我在开头新建了变量“总页数”，然后对“总页数”的判断语句禁用，并将其中的语句上移，最后禁用OCR提取中的 生成“总页数” ，直接使用手动输入“总页数”，可以正常使用该流。
以上仅是我懂一点代码的拙见，请见谅
![图片](https://github.com/user-attachments/assets/255ac975-62a2-4a3e-b2b4-36a0459a06dc)

**Comment by AfternoonMatcha** [comment]
非常感谢提交 issues！（还以为写出来没人用哩 qwq）由于微软 OCR 比较拉纯短数字的识别经常识别错误或失败导致总页数总是识别不上来。之后我尝试加一个校验来规避这个类型转换错误。另外提取出来的记录可至 [Matce.cn/WH](https://matce.cn/WH) 进行存档完善与合并，该网页亦开源于此仓库，可以试试看？（基本上能用了，接下来就是数据统计分析的开发了（）

**Comment by ShenYunyao1** [comment]
您好，我使用了您的网站，据我了解目前该网站只能排查OCR抽卡记录后的错误，另外“查看报告”按钮点击无反应。还有，请问可以做出可视化的抽卡分析面板吗，让用户能直观的看到出红抽数以及是否up，另外，是否可以做一个离线客户端使用。（我进您的网站需要关闭梯子，给您回复又要打开梯子（悲））

**Comment by TheZhiheng223** [comment]
您好，我使用了您的网站，据我了解目前该网站只能排查OCR抽卡记录后的错误，另外“查看报告”按钮点击无反应。还有，请问可以做出可视化的抽卡分析面板吗，让用户能直观的看到出红抽数以及是否up，另外，是否可以做一个离线客户端使用。（我进您的网站需要关闭梯子，给您回复又要打开梯子（悲））

**Comment by AfternoonMatcha** [comment]
`查看报告` 就是数据分析的页面（还没写，在计划内 qwq）网站目前主要起到修复合并存档并下载到本地的作用（可以将多次到处的存档进行合并）。离线客户端暂时还没有精力实现，可以考虑拉取前端仓库至本地运行来暂时替代

**Comment by AfternoonMatcha** [comment]
[前端仓库本地运行方式](https://github.com/AfternoonMatcha/WuHua-Gacha-OCR-Export-Power-Automate?tab=readme-ov-file#%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E8%BF%90%E8%A1%8C%E6%96%B9%E5%BC%8F)

**Comment by ShenYunyao1** [comment]
好的大佬，非常感谢，我很期待您继续更新。另外，我仍是学生，也是有很多时间，我是否可以帮助您

**Comment by AfternoonMatcha** [comment]
也可以使用 build 后的前端版本（0.3.1），解压并将其中文件放置到例如 Nginx 根目录即可运行：
[dist.zip](https://github.com/user-attachments/files/16492289/dist.zip)

**Comment by AfternoonMatcha** [comment]
> 好的大佬，非常感谢，我很期待您继续更新。另外，我仍是学生，也是有很多时间，我是否可以帮助您

当然可以，欢迎光临我们咖啡厅（直接来水群（雾：https://qm.qq.com/q/tLqRGI4BgI
